//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCENTE()
        {
            this.DOCENTE1 = new HashSet<DOCENTE>();
            this.REGISTROACADEMICO = new HashSet<REGISTROACADEMICO>();
            this.PERIODOACADEMICO = new HashSet<PERIODOACADEMICO>();
        }
    
        public int ID_DOCENTE { get; set; }
        public int ID_CARRERA { get; set; }
        public Nullable<int> ID_COORDINADOR { get; set; }
        public int ID_ROL { get; set; }
        public string PRIMERNOMBREDOCENTE { get; set; }
        public string SEGUNDONOMBREDOCENTE { get; set; }
        public string PRIMERAPELLIDODOCENTE { get; set; }
        public string SEGUNDOAPELLIDODOCENTE { get; set; }
        public string EMAILDOCENTE { get; set; }
        public string CEDULADOCENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCENTE> DOCENTE1 { get; set; }
        public virtual DOCENTE DOCENTE2 { get; set; }
        public virtual ROL ROL { get; set; }
        public virtual CARRERA CARRERA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTROACADEMICO> REGISTROACADEMICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERIODOACADEMICO> PERIODOACADEMICO { get; set; }
    }
}
