//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogInEntities : DbContext
    {
        public LogInEntities()
            : base("name=LogInEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOCENTE> DOCENTE { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<CARRERA> CARRERA { get; set; }
        public virtual DbSet<ESTADOESTUDIANTE> ESTADOESTUDIANTE { get; set; }
        public virtual DbSet<ESTADOPERIODO> ESTADOPERIODO { get; set; }
        public virtual DbSet<ESTUDIANTE> ESTUDIANTE { get; set; }
        public virtual DbSet<FACULTAD> FACULTAD { get; set; }
        public virtual DbSet<MATERIA> MATERIA { get; set; }
        public virtual DbSet<NIVELMATERIA> NIVELMATERIA { get; set; }
        public virtual DbSet<PARALELO> PARALELO { get; set; }
        public virtual DbSet<PERIODOACADEMICO> PERIODOACADEMICO { get; set; }
        public virtual DbSet<REGISTROACADEMICO> REGISTROACADEMICO { get; set; }
        public virtual DbSet<TUTORIA> TUTORIA { get; set; }
    }
}
