//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIODOACADEMICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERIODOACADEMICO()
        {
            this.REGISTROACADEMICO = new HashSet<REGISTROACADEMICO>();
            this.DOCENTE = new HashSet<DOCENTE>();
        }
    
        public int ID_PERIODOACADEMICO { get; set; }
        public Nullable<int> ID_ESTADOPERIODO { get; set; }
        public string ANIOPERIODO { get; set; }
        public string PERIODO { get; set; }
        public System.DateTime FECHAINICIOPERIODO { get; set; }
        public Nullable<System.DateTime> FECHAFINPERIODO { get; set; }
    
        public virtual ESTADOPERIODO ESTADOPERIODO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTROACADEMICO> REGISTROACADEMICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCENTE> DOCENTE { get; set; }
    }
}
