//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTROACADEMICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTROACADEMICO()
        {
            this.TUTORIA = new HashSet<TUTORIA>();
        }
    
        public int ID_DOCENTE { get; set; }
        public int ID_PERIODOACADEMICO { get; set; }
        public int ID_ESTADOESTUDIANTE { get; set; }
        public int ID_PARALELO { get; set; }
        public int ID_MATERIA { get; set; }
        public int ID_ESTUDIANTE { get; set; }
        public Nullable<decimal> NOTAPROGRESO1 { get; set; }
        public Nullable<decimal> NOTAPROGRESO2 { get; set; }
        public Nullable<decimal> NOTAEXAMENFINAL { get; set; }
        public string TIPOMATRICULA { get; set; }
    
        public virtual DOCENTE DOCENTE { get; set; }
        public virtual ESTADOESTUDIANTE ESTADOESTUDIANTE { get; set; }
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual MATERIA MATERIA { get; set; }
        public virtual PARALELO PARALELO { get; set; }
        public virtual PERIODOACADEMICO PERIODOACADEMICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUTORIA> TUTORIA { get; set; }
    }
}
