//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUTORIA
    {
        public int ID_TUTORIA { get; set; }
        public int ID_DOCENTE { get; set; }
        public int ID_PERIODOACADEMICO { get; set; }
        public int ID_ESTADOESTUDIANTE { get; set; }
        public int ID_PARALELO { get; set; }
        public int ID_MATERIA { get; set; }
        public int ID_ESTUDIANTE { get; set; }
        public string TEMATUTORIA { get; set; }
        public System.DateTime FECHATUTORIA { get; set; }
        public int TIEMPOTUTORIA { get; set; }
    
        public virtual REGISTROACADEMICO REGISTROACADEMICO { get; set; }
    }
}
